name: Deploy API Gateway

on:
    workflow_call:
      inputs:
        environment:
          type: string
          required: true

env:
  AWS_REGION: us-east-1

jobs:
  jobApiGateway:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install AWS CDK and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aws-cdk-lib
        npm install -g aws-cdk

    - name: Bootstrap CDK (if necessary)
      run: cdk bootstrap

    - name: Read environment configuration
      id: read-env-config
      run: |
        CONFIG=$(jq -r ".${{ inputs.environment }}" ./infra/config.json)
        echo "aws_account=$(echo $CONFIG | jq -r '.aws_account')" >> $GITHUB_ENV
        echo "aws_region=$(echo $CONFIG | jq -r '.aws_region')" >> $GITHUB_ENV
        echo "aws_assume_role_arn=$(echo $CONFIG | jq -r '.aws_assume_role_arn')" >> $GITHUB_ENV

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.aws_assume_role_arn }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.aws_region }}

    - name: Deploy Stack
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          cdk deploy --context lambda_handler_arn=${{ secrets.LAMBDA_PROD_ARN }}
        else
          cdk deploy --context lambda_handler_arn=${{ secrets.LAMBDA_DEV_ARN }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
